### ISSUE TITLE
Trying to get current window

### ISSUE THREAD

**Issue by BoxedFruits** [marwan-at-work/iterm2#1]
I would like to get the current window that iterm is running in and am having trouble implementing it since I am new to Go as well as working with Protobufs.

When I use `FocusRequest` it only gives me the state of the first window despite there being multiple windows. I expected it to show me all the tabs, windows and window statuses of everything.

Is there a different protobuf message I should be sending?

**Comment by BoxedFruits** [comment]
@marwan-at-work

**Comment by marwan-at-work** [comment]
If you call `.ListSessions` on a Tab interface, then call `.Activate` on the session/pane you're interested in, it should bring it to focus.
