### ISSUE TITLE
[Feature Request] Get current session from `app.current_window.current_tab.current_session`

### ISSUE THREAD

**Issue by lonnywong** [marwan-at-work/iterm2#2]
The Python API:
```py
app = await iterm2.async_get_app(connection)
current_session = app.current_window.current_tab.current_session
```

**Comment by marwan-at-work** [comment]
You would need the current_window_id which I'm not sure how the python code determines it, as I don't see a method defined here: https://github.com/gnachman/iTerm2/blob/1ebd3de45a1535b0e5eafd48b1cda37d3e5ae69e/proto/api.proto

Here's the current_window method https://github.com/gnachman/iTerm2/blob/1ebd3de45a1535b0e5eafd48b1cda37d3e5ae69e/api/library/python/iterm2/iterm2/app.py#L436

**Comment by lonnywong** [comment]
https://github.com/gnachman/iTerm2/blob/1ebd3de45a1535b0e5eafd48b1cda37d3e5ae69e/api/library/python/iterm2/iterm2/app.py#L365-L377

**Comment by lonnywong** [comment]
I can search the current session by the environment `ITERM_SESSION_ID`.

**Comment by lonnywong** [comment]
Can we get the session id of the sessions?
